import { useEffect, useMemo, type ComponentProps } from 'react';
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { clone as cloneSkinned } from 'three/examples/jsm/utils/SkeletonUtils.js';
import type { Appearance } from '@agent-hq/protocol';

// Models are generated by assets/blender/build_assets.py and served from
// /models. Materials are named so instances can be recolored.

export const MODEL_NAMES = [
  'character', 'desk', 'monitor', 'keyboard', 'chair', 'boss_chair', 'boss_desk', 'plant', 'plant_tall',
  'sofa', 'coffee_table', 'coffee_machine', 'whiteboard', 'elevator', 'floor_lamp', 'tree', 'tree_round',
] as const;
export type ModelName = (typeof MODEL_NAMES)[number];

const url = (name: ModelName) => `${import.meta.env.BASE_URL}models/${name}.glb`;
for (const name of MODEL_NAMES) useGLTF.preload(url(name));

function prepare(root: THREE.Object3D, recolor?: Record<string, string>, replace?: Record<string, THREE.Material>) {
  root.traverse((o) => {
    const mesh = o as THREE.Mesh;
    if (!mesh.isMesh) return;
    mesh.castShadow = true;
    mesh.receiveShadow = true;
    const material = mesh.material as THREE.MeshStandardMaterial;
    if (replace?.[material.name]) {
      mesh.material = replace[material.name];
      mesh.castShadow = false;
    } else if (recolor?.[material.name]) {
      const m = material.clone();
      m.color.set(recolor[material.name]);
      mesh.material = m;
    }
  });
  return root;
}

/** A static model instance. `recolor` maps material names to colors; `replace` swaps materials outright. */
export function Model(props: {
  name: ModelName;
  recolor?: Record<string, string>;
  replace?: Record<string, THREE.Material>;
} & Omit<ComponentProps<'group'>, 'children'>) {
  const { name, recolor, replace, ...group } = props;
  const { scene } = useGLTF(url(name));
  const key = JSON.stringify(recolor ?? {});
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const object = useMemo(() => prepare(scene.clone(true), recolor, replace), [scene, key, replace]);
  return (
    <group {...group}>
      <primitive object={object} />
    </group>
  );
}

export type CharacterClip = 'Stand' | 'Walk' | 'SitIdle' | 'SitType' | 'SitWave' | 'SitError';

const HAIR_NODES = { short: 'Hair_Short', long: 'Hair_Long', bun: 'Hair_Bun' } as const;

/** The rigged Blender character, recolored per agent and driven by named animation clips. */
export function Character(props: { appearance: Appearance; clip: CharacterClip; phase?: number; outfit?: 'casual' | 'suit' }) {
  const { appearance, clip, phase = 0, outfit = 'casual' } = props;
  const { scene, animations } = useGLTF(url('character'));

  const model = useMemo(() => {
    const c = cloneSkinned(scene);
    prepare(c, { Skin: appearance.skin, Hair: appearance.hair, Shirt: appearance.shirt });
    for (const [style, node] of Object.entries(HAIR_NODES)) {
      const obj = c.getObjectByName(node);
      if (obj) obj.visible = appearance.hairStyle === style;
    }
    c.traverse((o) => { if (o.name.startsWith('Outfit_Suit')) o.visible = outfit === 'suit'; });
    return c;
  }, [scene, appearance.skin, appearance.hair, appearance.shirt, appearance.hairStyle, outfit]);

  const mixer = useMemo(() => new THREE.AnimationMixer(model), [model]);
  useFrame((_, dt) => mixer.update(Math.min(dt, 0.1)));
  useEffect(() => () => { mixer.stopAllAction(); }, [mixer]);

  useEffect(() => {
    const source = THREE.AnimationClip.findByName(animations, clip);
    if (!source) return;
    const action = mixer.clipAction(source);
    action.reset();
    action.time = (phase * source.duration) % source.duration;
    action.fadeIn(0.3).play();
    return () => { action.fadeOut(0.3); };
  }, [clip, mixer, animations, phase]);

  return <primitive object={model} />;
}
